baseURL = "/"
languageCode = "en-us"
title = "Ako"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = ''
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Expressive HTTP middleware framework for deno using async functions. Aiming to port Koa to Deno."
    meta_og_title = "Ako"
    meta_og_type = "website"
    meta_og_url = "https://ako.land"
    meta_og_image = ""
    meta_og_description = "Expressive HTTP middleware framework for deno using async functions. Aiming to port Koa to Deno."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
